### PR TITLE
FF & IE fixes (no mouseenter needed, ensure ng-model initial value is shown correctly)

### PR DESCRIPTION
**Pull request by alexGofore**
* Removed browser specific tests for iframe initialization (iframe load event is triggered also by Chrome if the element is injected from JS)
* Fix editor initialization in Firefox & IE (ng-model initial value was not shown)

### CODE REVIEW

**Comment by mkoryak** [comment]
Cool, have you tested this on IE? I remember the init code being there because squire had a bug with initializing on a hidden iframe, though I think it was fixed recently. 

Can you test this code by running it on an element that starts out hidden and is later shown?

**Comment by alexGofore** [comment]
The demo page with updated sources can be tested here: http://veisto.tracr.org/angular-squire/dist/

I tested it with IE 9, IE 10, Firefox (Linux version 41.0.2) and Chrome (version 46.0.x).

> Can you test this code by running it on an element that starts out hidden and is later shown?
The second input on the demo page (which is initially hidden) works correctly (also in IE)

The only problem I spotted was that the cover-version doesn't work with IE 10 (but this was already mentioned from before).

**Comment by mkoryak** [comment]
Awesome! Thanks for the PR. Do you want me to publish a new version on npm/bower ?

**Comment by alexGofore** [comment]
I'm glad to help! And thank you for this project, it was very helpful to me. I don't use npm/bower in the current project, so I don't necessarily need a new version. But of course, if you think that my PR makes it better (as I hope), then probably someone else will appreciate an updated version :)

**Pull request merged**
